services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fraud_api

    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: dashboard/Dockerfile

    container_name: fraud_dashboard

    ports:
      - "8501:8501"

    depends_on:
      - backend